name: 'dbt_churn_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_churn_pipeline'

model-paths: ["dbt_models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_churn_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
